name:                json2csv
version:             0.1.0.0
github:              "danslapman/json2csv"
license:             BSD3
author:              "Daniil Smirnov"
maintainer:          "danslapman@gmail.com"
copyright:           "2018 Daniil Smirnov"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/json2csv#readme>

dependencies:
- base >= 4.7 && < 5
- text
- text-show
- bytestring
- aeson
- vector
- containers
- unordered-containers
- lens
- lens-aeson
- monad-loops
- hashable
- deepseq
- optparse-applicative
- optparse-text
- terminal-progress-bar

library:
  source-dirs: src
  ghc-options:
  - -fwarn-incomplete-patterns
  - -fwarn-unused-imports

executables:
  json2csv:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -fwarn-incomplete-patterns
    - -fwarn-unused-imports
    dependencies:
    - json2csv

tests:
  json2csv-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -fwarn-incomplete-patterns
    - -fwarn-unused-imports
    dependencies:
    - json2csv
    - HUnit
